version: 2.1.1.{build}

os: Visual Studio 2022

configuration: Release

branches:
  only:
    - develop
    - develop-v2
    - /v*/

environment:
  # Version Suffix
  version_suffix: alpha

install:
  - ps: .\build\appveyor-semver.ps1
  - ps: .\build\check-release-version.ps1
  - ps: Update-AppveyorBuild -Version $Env:semver

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '$(semver)'
  assembly_version: '$(appveyor_file_version)'
  file_version: '$(appveyor_file_version)'
  informational_version: '$(semver)'

build_script:
- cmd: >-
    cd build

    npm install

    node patch-package-manifest.js

    cd..

    cd src

    cd CloudflareImageUrlGenerator

    dotnet build

    cd..

artifacts:
  - path: .\src\CloudflareImageUrlGenerator\bin\$(CONFIGURATION)\*.nupkg

deploy:
    # Umbraco MyGet community feed
  - provider: NuGet
    server: https://www.myget.org/F/umbraco-packages/api/v2/package
    symbol_server: https://www.myget.org/F/umbraco-packages/symbols/api/v2/package
    api_key:
      secure: SASQGWG/4zNns7bwSSsJ5RPvKcKfJsBeEPuw69wsVPA3PO739QmzVtc5VwQwgvbr
    artifact: /.*\.nupkg/
    on:
      branch: develop

    # Umbraco MyGet community feed
  - provider: NuGet
    server: https://www.myget.org/F/umbraco-packages/api/v2/package
    symbol_server: https://www.myget.org/F/umbraco-packages/symbols/api/v2/package
    api_key:
      secure: SASQGWG/4zNns7bwSSsJ5RPvKcKfJsBeEPuw69wsVPA3PO739QmzVtc5VwQwgvbr
    artifact: /.*\.nupkg/
    on:
      branch: develop-v2